# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x1a\x0cnanopb.proto\"/\n\x0c\x61\x63\x63\x65l_data_t\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\".\n\x0bgyro_data_t\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"}\n\nimu_data_t\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.HAL_status_e\x12(\n\naccel_data\x18\x02 \x03(\x0b\x32\r.accel_data_tB\x05\x92?\x02\x10\x64\x12&\n\tgyro_data\x18\x03 \x03(\x0b\x32\x0c.gyro_data_tB\x05\x92?\x02\x10\x64*H\n\x0cHAL_status_e\x12\n\n\x06HAL_OK\x10\x00\x12\r\n\tHAL_ERROR\x10\x01\x12\x0c\n\x08HAL_BUSY\x10\x02\x12\x0f\n\x0bHAL_TIMEOUT\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMU_DATA_T.fields_by_name['accel_data']._options = None
  _IMU_DATA_T.fields_by_name['accel_data']._serialized_options = b'\222?\002\020d'
  _IMU_DATA_T.fields_by_name['gyro_data']._options = None
  _IMU_DATA_T.fields_by_name['gyro_data']._serialized_options = b'\222?\002\020d'
  _HAL_STATUS_E._serialized_start=251
  _HAL_STATUS_E._serialized_end=323
  _ACCEL_DATA_T._serialized_start=27
  _ACCEL_DATA_T._serialized_end=74
  _GYRO_DATA_T._serialized_start=76
  _GYRO_DATA_T._serialized_end=122
  _IMU_DATA_T._serialized_start=124
  _IMU_DATA_T._serialized_end=249
# @@protoc_insertion_point(module_scope)
