# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsm6ds.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clsm6ds.proto\"4\n\ttemp_data\x12\x0c\n\x04tick\x18\x01 \x01(\r\x12\x0c\n\x04temp\x18\x02 \x01(\x02\x12\x0b\n\x03\x65rr\x18\x03 \x01(\r\"7\n\tmsg_oneof\x12#\n\rmsg_temp_data\x18\x01 \x01(\x0b\x32\n.temp_dataH\x00\x42\x05\n\x03msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lsm6ds_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMP_DATA._serialized_start=16
  _TEMP_DATA._serialized_end=68
  _MSG_ONEOF._serialized_start=70
  _MSG_ONEOF._serialized_end=125
# @@protoc_insertion_point(module_scope)
