/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "imu.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(accel_data_t, accel_data_t, AUTO)


PB_BIND(gyro_data_t, gyro_data_t, AUTO)


PB_BIND(imu_data_t, imu_data_t, 2)




