/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "lsm6ds.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(temp_data, temp_data, AUTO)


PB_BIND(msg_oneof, msg_oneof, AUTO)



